name: url_params
description: This package helps to add query parameters to a Dart
  that appends the '?param1=one&param2=two' to the url.
version: 1.1.1
homepage: https://github.com/ishaileshmishra/url_params

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.1
  path: ^1.6.0
  logger: ^0.9.1
  dio: ^4.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.4.1
  lint: ^1.1.1
