name: url_params
description: This package helps to add query parameters to a Dart
  that appends the '?param1=one&param2=two' to the url.
version: 1.1.1
homepage: https://github.com/ishaileshmishra/url_params

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  path: ^1.8.3
  logger: ^1.3.0
  dio: ^5.1.2
